name: videostreming_venugopal_com_siddhi_company
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Art_Craft.svg
    - assets/Business.svg
    - assets/Career.svg
    - assets/Crime.svg
    - assets/Education.svg
    - assets/English_Speaking.svg
    - assets/Finance.svg
    - assets/Fitness.svg
    - assets/Frame.png
    - assets/Frame2.png
    - assets/Free_Videos.svg
    - assets/Govt_Job.svg
    - assets/Health.svg
    - assets/Instagram.svg
    - assets/Mobile_Tricks.svg
    - assets/News.svg
    - assets/Sarkari_Kaam.svg
    - assets/seekho.jpeg
    - assets/Sports.svg
    - assets/Stock_Market.svg
    - assets/Success.svg
    - assets/Technology.svg
    - assets/View_All.svg
    - assets/Youtube.svg
    - assets/Part_Time.svg